### ISSUE TITLE
Import error when trying to load the updated server on AWS instance

### ISSUE THREAD

**Issue by yonikesel1** [yonikesel1/sushi-dashboard#2]
I am getting import error when I'm trying to npm start on AWS instance.
On my local machine this syntax is working.

Could this be due to mismatch in node version between local machine and the AWS instance?
Or could this be due to different OS?

this is the error message:

/home/ubuntu/sushi-dashboard/server.mjs:1
import pkg1 from "graphql";
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by lmilbaum** [comment]
@yonikesel1 Check if the code has CRLF charcters. Those are generated on a windows OS to represent and end of line.  BTW, am I supposed to solve the problem or only help you to solve it? If the latter then maybe you want to reassign it to you and ping me here for my help.

**Comment by yonikesel1** [comment]
The problem occurred because I was trying to run npm start from the ubuntu machine directly and no with node image.
managed to run the the instance with the latest code.
